# Nome do nosso workflow. Aparecerá na aba "Actions" do GitHub.
name: Commit Automático Diário

# Define quando o workflow deve ser executado.
on:
  workflow_dispatch: # Permite que você execute este workflow manualmente na interface do GitHub.
  schedule:
    # Executa "às 00:00 UTC todos os dias".
    # A sintaxe é baseada no 'cron'. Você pode usar https://crontab.guru/ para criar seu próprio cronograma.
    - cron: '0 0 * * *'

# Define os "trabalhos" (jobs) que o workflow vai executar.
jobs:
  auto_commit_job:
    # O tipo de máquina virtual que o job vai rodar. 'ubuntu-latest' é uma boa escolha padrão.
    runs-on: ubuntu-latest

    # Os passos que serão executados no job.
    steps:
      # Passo 1: Fazer o checkout do código do seu repositório
      # Isso "baixa" o seu código para a máquina virtual para que o script possa trabalhar com ele.
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # Passo 2: Alterar um arquivo para criar uma mudança
      # Este comando adiciona uma linha com a data e hora atual ao final do arquivo update_log.md.
      # Se o arquivo não existir, ele será criado.
      - name: Modificar o arquivo de log
        run: echo "Atualizado em $(date)" >> update_log.md

      # Passo 3: Configurar o Git com o nome e e-mail do "committer"
      # O GitHub Actions precisa saber quem está fazendo o commit.
      # Usamos um usuário genérico do GitHub Actions aqui.
      - name: Configurar Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      # Passo 4: Fazer o commit das alterações
      # Adiciona todos os arquivos modificados e faz o commit com uma mensagem dinâmica.
      - name: Fazer o Commit das alterações
        run: |
          git add .
          git commit -m "Commit automático: Atualização do log em $(date)"

      # Passo 5: Fazer o Push para o repositório
      # Envia o commit para o branch principal (main) do seu repositório.
      - name: Fazer o Push das alterações
        run: git push