name: Commit Automático Diário

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  auto_commit_job:
    runs-on: ubuntu-latest

    # ADICIONE ESTA SEÇÃO PARA DAR PERMISSÃO DE ESCRITA
    permissions:
      contents: write

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Modificar o arquivo de log
        run: echo "Atualizado em $(date)" >> update_log.md

      - name: Configurar Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Fazer o Commit das alterações
        run: |
          git add .
          git commit -m "Commit automático: Atualização do log em $(date)"

      - name: Fazer o Push das alterações
        run: git push
